package project;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class GUI_Driver extends javax.swing.JFrame implements Runnable {

    public static OS os;
    public boolean isPaused = true;
    private int timeUnitLength;
    private Thread guiUpdateThread;
    
    /**
     * Creates new form GUI_Driver
     */
    public GUI_Driver(OS os) {
        this.os = os;
        //this.timeUnitLength = os.getTimeUnitLength();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_startPause = new javax.swing.JToggleButton();
        waitingProcessQueueLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cpu1_Status = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_report = new javax.swing.JTextArea();
        lbl_timeUnit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        var_time = new javax.swing.JFormattedTextField();
        lbl_pause_play = new javax.swing.JLabel();
        button_timeunit = new javax.swing.JButton();
        lbl_cpu1 = new javax.swing.JLabel();
        lbl_cpu2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        cpu2_Status = new javax.swing.JTextArea();
        lbl_processName = new javax.swing.JLabel();
        lbl_serviceTime = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_readyQueue = new javax.swing.JTextArea();
        lbl_report_name = new javax.swing.JLabel();
        lbl_report_arrive = new javax.swing.JLabel();
        lbl_report_service = new javax.swing.JLabel();
        lbl_report_TAT = new javax.swing.JLabel();
        lbl_report_finish = new javax.swing.JLabel();
        lbl_report_nTAT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button_startPause.setText("Start/Pause");
        button_startPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_startPauseActionPerformed(evt);
            }
        });

        waitingProcessQueueLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        waitingProcessQueueLabel.setText("OS Ready Queue");

        cpu1_Status.setEditable(false);
        cpu1_Status.setColumns(20);
        cpu1_Status.setLineWrap(true);
        cpu1_Status.setRows(5);
        cpu1_Status.setWrapStyleWord(true);
        cpu1_Status.setAutoscrolls(false);
        cpu1_Status.setBorder(null);
        //cpu1_Status.setEnabled(false);
        jScrollPane2.setViewportView(cpu1_Status);

        table_report.setEditable(false);
        table_report.setColumns(20);
        table_report.setRows(5);
        jScrollPane3.setViewportView(table_report);

        lbl_timeUnit.setText("1 Time Unit =");

        jLabel1.setText("ms");

        var_time.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        var_time.setValue(os.getTimeUnitLength());

        lbl_pause_play.setText("System Paused");

        button_timeunit.setText("Update");
        button_timeunit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_timeunitActionPerformed(evt);
            }
        });

        lbl_cpu1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_cpu1.setText("CPU1");

        lbl_cpu2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_cpu2.setText("CPU2");

        cpu2_Status.setEditable(false);
        cpu2_Status.setColumns(20);
        cpu2_Status.setLineWrap(true);
        cpu2_Status.setRows(5);
        cpu2_Status.setWrapStyleWord(true);
        cpu2_Status.setAutoscrolls(false);
        cpu2_Status.setBorder(null);
        jScrollPane5.setViewportView(cpu2_Status);

        lbl_processName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_processName.setText("Process Name");

        lbl_serviceTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_serviceTime.setText("Service Time");
        lbl_serviceTime.setMaximumSize(new java.awt.Dimension(70, 14));
        lbl_serviceTime.setMinimumSize(new java.awt.Dimension(70, 14));

        table_readyQueue.setEditable(false);
        table_readyQueue.setColumns(20);
        table_readyQueue.setRows(5);
        jScrollPane4.setViewportView(table_readyQueue);

        lbl_report_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_report_name.setText("Process Name");

        lbl_report_arrive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_report_arrive.setText("Arrive Time");
        lbl_report_arrive.setMaximumSize(new java.awt.Dimension(70, 14));
        lbl_report_arrive.setMinimumSize(new java.awt.Dimension(70, 14));

        lbl_report_service.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_report_service.setText("Service Time");
        lbl_report_service.setMaximumSize(new java.awt.Dimension(70, 14));
        lbl_report_service.setMinimumSize(new java.awt.Dimension(70, 14));

        lbl_report_TAT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_report_TAT.setText("TAT");
        lbl_report_TAT.setMaximumSize(new java.awt.Dimension(70, 14));
        lbl_report_TAT.setMinimumSize(new java.awt.Dimension(70, 14));

        lbl_report_finish.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_report_finish.setText("Finish Time");
        lbl_report_finish.setMaximumSize(new java.awt.Dimension(70, 14));
        lbl_report_finish.setMinimumSize(new java.awt.Dimension(70, 14));

        lbl_report_nTAT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_report_nTAT.setText("nTAT");
        lbl_report_nTAT.setMaximumSize(new java.awt.Dimension(70, 14));
        lbl_report_nTAT.setMinimumSize(new java.awt.Dimension(70, 14));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_report_name, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_report_arrive, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_report_service, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_report_finish, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_report_TAT, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_report_nTAT, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(waitingProcessQueueLabel)
                            .addComponent(button_startPause, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbl_processName, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_serviceTime, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_timeUnit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(var_time, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(button_timeunit))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_cpu1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_cpu2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(lbl_pause_play))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_startPause)
                    .addComponent(lbl_pause_play))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waitingProcessQueueLabel)
                    .addComponent(lbl_timeUnit)
                    .addComponent(jLabel1)
                    .addComponent(var_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_timeunit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_processName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_serviceTime, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_report_name, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_report_arrive, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_report_service, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_report_finish, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_report_TAT, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_report_nTAT, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lbl_cpu1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(lbl_cpu2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_startPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_startPauseActionPerformed
        // TODO add your handling code here:
        if (isPaused) lbl_pause_play.setText("System Running");
        else lbl_pause_play.setText("System Paused");
        isPaused = !isPaused;
        os.setIsPaused(isPaused);
        if(isPaused){
            os.stopCPUs();
            this.stopGUIUpdater();
        }
        else {
            os.startCPUs();
            this.startGUIUpdater();
        }
    }//GEN-LAST:event_button_startPauseActionPerformed

    private void button_timeunitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_timeunitActionPerformed
        int num = ((Number)(var_time.getValue())).intValue();
        os.setTimeUnitLength(num);
        //this.timeUnitLength = os.getTimeUnitLength();
    }//GEN-LAST:event_button_timeunitActionPerformed

    //Removed main function
    //All main functionality in Main class

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton button_startPause;
    private javax.swing.JButton button_timeunit;
    private javax.swing.JTextArea cpu1_Status;
    private javax.swing.JTextArea cpu2_Status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbl_cpu1;
    private javax.swing.JLabel lbl_cpu2;
    private javax.swing.JLabel lbl_pause_play;
    private javax.swing.JLabel lbl_processName;
    private javax.swing.JLabel lbl_report_TAT;
    private javax.swing.JLabel lbl_report_arrive;
    private javax.swing.JLabel lbl_report_finish;
    private javax.swing.JLabel lbl_report_nTAT;
    private javax.swing.JLabel lbl_report_name;
    private javax.swing.JLabel lbl_report_service;
    private javax.swing.JLabel lbl_serviceTime;
    private javax.swing.JLabel lbl_timeUnit;
    private javax.swing.JTextArea table_readyQueue;
    private javax.swing.JTextArea table_report;
    private javax.swing.JFormattedTextField var_time;
    private javax.swing.JLabel waitingProcessQueueLabel;
    // End of variables declaration//GEN-END:variables


    /**
    * Actions that need to be performed at each timestep, including updating all info displays.  
    */ 
    private void timeStep(){
        cpu1_Status.setText(this.os.getCPUList().get(0).displayStatus());
        cpu2_Status.setText(this.os.getCPUList().get(1).displayStatus());
        table_readyQueue.setText(this.os.displayQueueState());
        table_report.setText(this.os.displayStatus());
    }

    /**
    * Starts thread for GUI Updates when the system starts playing.
    */
    public void startGUIUpdater()
    {
        Thread t = new Thread(this);    // add start thread for gui updates
        this.guiUpdateThread = t;
        t.start();
        System.out.println("Started the GUI Updater thread");
    }

    /**
    * Interrupt GUI Updater Thread when the system pauses;
    */
    public void stopGUIUpdater()
    {
        this.guiUpdateThread.interrupt();
    }   
     
    /**
    * Run timeStep updates once every time step.
    */
    public void run(){
        System.out.println("  ...  GIU updater thread starting ");

        while(true){
            this.timeStep();
            try {
                Thread.sleep((long)(os.getTimeUnitLength()));
            } 
            catch (InterruptedException ex) {
            // TBD catch and deal with exception ere
                System.out.println("GUI Driver Exception caught: " + ex);
                this.timeStep();
                return;
            }
        }
    }
}   
