package project;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class GUI_Driver extends javax.swing.JFrame {

    public static OS os;
    public boolean isPaused = true;
    
    /**
     * Creates new form GUI_Driver
     */
    public GUI_Driver(OS os) {
        this.os = os;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startPauseToggleButton = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        waitingProcessQueueTable = new javax.swing.JTable();
        waitingProcessQueueLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cpu1_Status = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        systemReportArea = new javax.swing.JTextArea();
        systemReportLabel = new javax.swing.JLabel();
        lbl_timeUnit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        var_time = new javax.swing.JFormattedTextField();
        lbl_pause_play = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        startPauseToggleButton.setText("Start/Pause");
        startPauseToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startPauseToggleButtonActionPerformed(evt);
            }
        });

        waitingProcessQueueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Process Name", "Service Time"
            }
        ));
        waitingProcessQueueTable.getTableHeader().setReorderingAllowed(false);
        waitingProcessQueueTable.setEnabled(false);
        jScrollPane1.setViewportView(waitingProcessQueueTable);

        waitingProcessQueueLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        waitingProcessQueueLabel.setText("Waiting Process Queue");

        cpu1_Status.setColumns(20);
        cpu1_Status.setRows(5);
        cpu1_Status.setWrapStyleWord(true);
        cpu1_Status.setEnabled(false);
        jScrollPane2.setViewportView(cpu1_Status);

        systemReportArea.setColumns(20);
        systemReportArea.setRows(5);
        systemReportArea.setEnabled(false);
        jScrollPane3.setViewportView(systemReportArea);

        systemReportLabel.setText("System Report Stats");

        lbl_timeUnit.setText("1 Time Unit = ");

        jLabel1.setText("ms");

        var_time.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        var_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var_timeActionPerformed(evt);
            }
        });
        var_time.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                var_timePropertyChange(evt);
            }
        });

        lbl_pause_play.setText("System Paused");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(waitingProcessQueueLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startPauseToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_timeUnit)
                                        .addGap(3, 3, 3)
                                        .addComponent(var_time, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(lbl_pause_play))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(systemReportLabel))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startPauseToggleButton)
                    .addComponent(lbl_pause_play))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waitingProcessQueueLabel)
                    .addComponent(lbl_timeUnit)
                    .addComponent(jLabel1)
                    .addComponent(var_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(systemReportLabel)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startPauseToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startPauseToggleButtonActionPerformed
        // TODO add your handling code here:
        if (isPaused) lbl_pause_play.setText("System Running");
        else lbl_pause_play.setText("System Paused");
        isPaused = !isPaused;
        os.setIsPaused(isPaused);
    }//GEN-LAST:event_startPauseToggleButtonActionPerformed

    private void var_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_var_timeActionPerformed

    private void var_timePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_var_timePropertyChange
        Object source = evt.getSource();
        if (source == var_time) {
            int num = (Integer)(var_time.getValue());
        }
    }//GEN-LAST:event_var_timePropertyChange

    //Removed main function
    //All main functionality in Main class

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea cpu1_Status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_pause_play;
    private javax.swing.JLabel lbl_timeUnit;
    private javax.swing.JToggleButton startPauseToggleButton;
    private javax.swing.JTextArea systemReportArea;
    private javax.swing.JLabel systemReportLabel;
    private javax.swing.JFormattedTextField var_time;
    private javax.swing.JLabel waitingProcessQueueLabel;
    private javax.swing.JTable waitingProcessQueueTable;
    // End of variables declaration//GEN-END:variables
}
